import streamlit as st
import openai
import requests
import os
from apikey import OPENAI_API_KEY, FMP_API_KEY
openai.api_key = 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
